const randomWords = [
  'apple',
  'banana',
  'cherry',
  'orange',
  'grape',
  'watermelon',
  'pineapple',
  'strawberry',
  'blueberry',
  'mango',
  'kiwi',
  'pear',
  'lemon',
  'peach',
  'apricot',
  'plum',
  'pomegranate',
  'raspberry',
  'blackberry',
  'coconut',
  'avocado',
  'guava',
  'melon',
  'fig',
  'lime',
  'tangerine',
  'dragonfruit',
  'passionfruit',
  'papaya',
  'kiwifruit',
  'cranberry',
  'nectarine',
  'honeydew',
  'persimmon',
  'starfruit',
  'quince',
  'lychee',
  'gooseberry',
  'mulberry',
  'boysenberry',
  'elderberry',
  'cantaloupe',
  'date',
  'rhubarb',
  'grapefruit',
  'jackfruit',
  'kumquat',
  'olive',
  'pawpaw',
  'plantain',
  'rambutan',
  'soursop',
  'tamarind',
  'ugli fruit',
  'yuzu',
  'zucchini',
  'carrot',
  'broccoli',
  'potato',
  'tomato',
  'lettuce',
  'cabbage',
  'onion',
  'pepper',
  'pumpkin',
  'spinach',
  'cucumber',
  'cauliflower',
  'garlic',
  'beetroot',
  'eggplant',
  'asparagus',
  'corn',
  'mushroom',
  'bell pepper',
  'radish',
  'sweet potato',
  'celery',
  'leek',
  'shallot',
  'kale',
  'brussels sprout',
  'watercress',
  'artichoke',
  'turnip',
  'fennel',
  'okra',
  'cassava',
  'purslane',
  'jicama',
  'parsnip',
  'swiss chard',
  'bok choy',
  'endive',
  'bitter melon',
  'chayote',
  'daikon',
  'collard greens',
  'arugula',
  'horseradish',
  'yam',
  'water chestnut',
  'yucca',
  'spaghetti squash',
  'bamboo shoots',
  'chicory',
  'plantains',
  'jerusalem artichoke',
  'lotus root',
  'dandelion greens',
  'luffa',
  'kohlrabi',
  'parsley',
  'chamomile',
  'sage',
  'thyme',
  'oregano',
  'rosemary',
  'lavender',
  'mint',
  'basil',
  'coriander',
  'dill',
  'cilantro',
  'tarragon',
  'marjoram',
  'lemongrass',
  'bay leaves',
  'cardamom',
  'saffron',
  'turmeric',
  'nutmeg',
  'cinnamon',
  'cloves',
  'allspice',
  'vanilla',
  'anise',
  'ginger',
  'fennel seeds',
  'mustard seeds',
  'poppy seeds',
  'paprika',
  'cumin',
  'fenugreek',
  'celery seeds',
  'caraway',
  'chia seeds',
  'hemp seeds',
  'sesame seeds',
  'sunflower seeds',
  'flaxseeds',
  'pumpkin seeds',
  'quinoa',
  'bulgur',
  'millet',
  'couscous',
  'buckwheat',
  'barley',
  'spelt',
  'amaranth',
  'teff',
  'farro',
  'wild rice',
  'sorghum',
  'emmer',
  'rye',
  'oat groats',
  'lentils',
  'chickpeas',
  'black beans',
  'kidney beans',
  'pinto beans',
  'navy beans',
  'lima beans',
  'cannellini beans',
  'soybeans',
  'adzuki beans',
  'mung beans',
  'garbanzo beans',
  'fava beans',
  'black-eyed peas',
  'split peas',
  'green peas',
  'snow peas',
  'snap peas',
  'pea shoots',
  'pumpkin flowers',
  'artichoke hearts',
  'bamboo shoots',
  'coconut milk',
  'soy milk',
  'almond milk',
  'oat milk',
  'rice milk',
  'cashew milk',
  'hemp milk',
  'goat cheese',
  'blue cheese',
  'feta cheese',
  'cheddar cheese',
  'mozzarella cheese',
  'parmesan cheese',
  'brie cheese',
  'gouda cheese',
  'swiss cheese',
  'provolone cheese',
  'pepper jack cheese',
  'ricotta cheese',
  'cream cheese',
  'cottage cheese',
  'havarti cheese',
  'mascarpone cheese',
  'queso fresco',
  'queso blanco',
  'manchego cheese',
  'gorgonzola cheese',
  'roquefort cheese',
  'fontina cheese',
  'pecorino romano cheese',
  'gruyère cheese',
  'edam cheese',
  'asiago cheese',
  'camembert cheese',
  'cambozola cheese',
  'limburger cheese',
  'humboldt fog cheese',
  'haloumi cheese',
  'halloumi cheese',
  'paneer cheese',
  'saganaki cheese',
  'teleme cheese',
  'bel paese cheese',
  'buratta cheese',
  'burrata cheese',
  'ricotta salata cheese',
  'boursault cheese',
  'boursin cheese',
  'beemster cheese',
  'danish blue cheese',
  'caerphilly cheese',
  'cantal cheese',
  'gjetost cheese',
  'cabot cheese',
  'sharp cheddar cheese',
  'colby cheese',
  'colby jack cheese',
  'pepperjack cheese',
]

const getRandomWords = (count: number): string[] => randomWords.slice(0, count)

export const getRandomWordOptions = (count: number) => {
  return getRandomWords(count).map((word) => ({
    label: word.charAt(0).toUpperCase() + word.slice(1),
    value: word.split(' ').join('_').toLowerCase(),
  }))
}
